# Generated by Django 4.0.3 on 2022-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_character_armour_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar_of_choice',
            name='custom_avatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avatar_of_choice',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_agility',
            field=models.IntegerField(blank=b'I01\n', default=10, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_charisma',
            field=models.IntegerField(blank=b'I01\n', default=10, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_endurance',
            field=models.IntegerField(blank=b'I01\n', default=10, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_intelligence',
            field=models.IntegerField(blank=b'I01\n', default=10, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_strength',
            field=models.IntegerField(blank=b'I01\n', default=10, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_wisdom',
            field=models.IntegerField(blank=b'I01\n', default=10, null=b'I01\n'),
        ),
    ]
