# Generated by Django 4.0.3 on 2022-05-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_avatar_of_choice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='custom_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
