# Generated by Django 4.0.3 on 2022-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_avatar_of_choice_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar_of_choice',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
