# Generated by Django 4.0.3 on 2022-05-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_aspect_chr_alter_aspect_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequence',
            name='severity',
            field=models.CharField(default='Неуточненная травма', max_length=100),
        ),
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(default='Пустое дополнение', max_length=100),
        ),
        migrations.AlterField(
            model_name='stunt',
            name='name',
            field=models.CharField(default='Пустой трюк', max_length=100),
        ),
    ]
