# Generated by Django 4.0.3 on 2022-05-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_consequence_severity_alter_extra_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Физический', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('avaliable', models.IntegerField(default=3)),
                ('spent', models.IntegerField(default=0)),
                ('chr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_stress', to='main.character')),
            ],
        ),
    ]
