# Generated by Django 4.0.3 on 2022-05-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_stress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='max_skill',
        ),
        migrations.RemoveField(
            model_name='character',
            name='min_skill',
        ),
    ]
