# Generated by Django 4.0.3 on 2022-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_character_max_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Неуказанное умение', max_length=100),
        ),
    ]
